//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeDaiDuong_151901766
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Mota { get; set; }
        public string GioiTinh { get; set; }
        public string MaCD { get; set; }
        public Nullable<int> SoLuongAnh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string Hinh5 { get; set; }
        public string Hinh6 { get; set; }
        public string Hinh7 { get; set; }
        public string Hinh8 { get; set; }
        public string Hinh9 { get; set; }
        public string Hinh10 { get; set; }
        public string Hinh11 { get; set; }
        public string Hinh12 { get; set; }
        public string Hinh13 { get; set; }
        public string Hinh14 { get; set; }
        public string Hinh15 { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
